name: RSpec Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3', '3.4' ]

    name: Ruby ${{ matrix.ruby }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none  # Don't install bundler yet

      - name: Install compatible bundler
        shell: bash
        run: |
          if [[ "${{ matrix.ruby }}" == "2.5" ]]; then
            gem install bundler -v '~> 2.3.0'  # Bundler 2.0-2.3 for Ruby 2.3.0-2.5.x
          elif [[ "${{ matrix.ruby }}" =~ ^2\.[67] ]]; then
            gem install bundler -v '~> 2.4.0'  # Bundler 2.4 for Ruby 2.6.0-2.7.x
          elif [[ "${{ matrix.ruby }}" == "3.0" ]]; then
            gem install bundler -v '~> 2.5.0'  # Bundler 2.5 for Ruby 3.0.x
          else
            gem install bundler -v '~> 2.6.0'  # Bundler 2.6+ for Ruby 3.1.0+
          fi

      - name: Setup bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3 --with test --without development

      - name: Run specs
        run: bundle exec rspec
